// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.1
// source: internal/igservice/igservice.proto

package brfactorybackend

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateIGTVVideoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IgUsername   string `protobuf:"bytes,1,opt,name=igUsername,proto3" json:"igUsername,omitempty"`
	IgPassword   string `protobuf:"bytes,2,opt,name=igPassword,proto3" json:"igPassword,omitempty"`
	Title        string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Caption      string `protobuf:"bytes,4,opt,name=caption,proto3" json:"caption,omitempty"`
	VideoURL     string `protobuf:"bytes,5,opt,name=videoURL,proto3" json:"videoURL,omitempty"`
	ThumbnailURL string `protobuf:"bytes,6,opt,name=thumbnailURL,proto3" json:"thumbnailURL,omitempty"`
}

func (x *CreateIGTVVideoRequest) Reset() {
	*x = CreateIGTVVideoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_igservice_igservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateIGTVVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIGTVVideoRequest) ProtoMessage() {}

func (x *CreateIGTVVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_igservice_igservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIGTVVideoRequest.ProtoReflect.Descriptor instead.
func (*CreateIGTVVideoRequest) Descriptor() ([]byte, []int) {
	return file_internal_igservice_igservice_proto_rawDescGZIP(), []int{0}
}

func (x *CreateIGTVVideoRequest) GetIgUsername() string {
	if x != nil {
		return x.IgUsername
	}
	return ""
}

func (x *CreateIGTVVideoRequest) GetIgPassword() string {
	if x != nil {
		return x.IgPassword
	}
	return ""
}

func (x *CreateIGTVVideoRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateIGTVVideoRequest) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

func (x *CreateIGTVVideoRequest) GetVideoURL() string {
	if x != nil {
		return x.VideoURL
	}
	return ""
}

func (x *CreateIGTVVideoRequest) GetThumbnailURL() string {
	if x != nil {
		return x.ThumbnailURL
	}
	return ""
}

type CreateIGTVVideoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateIGTVVideoResponse) Reset() {
	*x = CreateIGTVVideoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_igservice_igservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateIGTVVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIGTVVideoResponse) ProtoMessage() {}

func (x *CreateIGTVVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_igservice_igservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIGTVVideoResponse.ProtoReflect.Descriptor instead.
func (*CreateIGTVVideoResponse) Descriptor() ([]byte, []int) {
	return file_internal_igservice_igservice_proto_rawDescGZIP(), []int{1}
}

func (x *CreateIGTVVideoResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_internal_igservice_igservice_proto protoreflect.FileDescriptor

var file_internal_igservice_igservice_proto_rawDesc = []byte{
	0x0a, 0x22, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x69, 0x67, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2f, 0x69, 0x67, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x69, 0x67, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x22, 0xc8,
	0x01, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x47, 0x54, 0x56, 0x56, 0x69, 0x64,
	0x65, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x67, 0x55,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69,
	0x67, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x67, 0x50,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69,
	0x67, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x61, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x61, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x69, 0x64,
	0x65, 0x6f, 0x55, 0x52, 0x4c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x76, 0x69, 0x64,
	0x65, 0x6f, 0x55, 0x52, 0x4c, 0x12, 0x22, 0x0a, 0x0c, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61,
	0x69, 0x6c, 0x55, 0x52, 0x4c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x68, 0x75,
	0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x55, 0x52, 0x4c, 0x22, 0x29, 0x0a, 0x17, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x49, 0x47, 0x54, 0x56, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x32, 0x63, 0x0a, 0x09, 0x49, 0x47, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x56, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x47, 0x54, 0x56, 0x56,
	0x69, 0x64, 0x65, 0x6f, 0x12, 0x20, 0x2e, 0x69, 0x67, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x47, 0x54, 0x56, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x69, 0x67, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x47, 0x54, 0x56, 0x56, 0x69, 0x64, 0x65,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x14, 0x5a, 0x12, 0x2e, 0x2f, 0x62,
	0x72, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_igservice_igservice_proto_rawDescOnce sync.Once
	file_internal_igservice_igservice_proto_rawDescData = file_internal_igservice_igservice_proto_rawDesc
)

func file_internal_igservice_igservice_proto_rawDescGZIP() []byte {
	file_internal_igservice_igservice_proto_rawDescOnce.Do(func() {
		file_internal_igservice_igservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_igservice_igservice_proto_rawDescData)
	})
	return file_internal_igservice_igservice_proto_rawDescData
}

var file_internal_igservice_igservice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_igservice_igservice_proto_goTypes = []interface{}{
	(*CreateIGTVVideoRequest)(nil),  // 0: igclient.CreateIGTVVideoRequest
	(*CreateIGTVVideoResponse)(nil), // 1: igclient.CreateIGTVVideoResponse
}
var file_internal_igservice_igservice_proto_depIdxs = []int32{
	0, // 0: igclient.IGService.CreateIGTVVideo:input_type -> igclient.CreateIGTVVideoRequest
	1, // 1: igclient.IGService.CreateIGTVVideo:output_type -> igclient.CreateIGTVVideoResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_igservice_igservice_proto_init() }
func file_internal_igservice_igservice_proto_init() {
	if File_internal_igservice_igservice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_igservice_igservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateIGTVVideoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_igservice_igservice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateIGTVVideoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_igservice_igservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_igservice_igservice_proto_goTypes,
		DependencyIndexes: file_internal_igservice_igservice_proto_depIdxs,
		MessageInfos:      file_internal_igservice_igservice_proto_msgTypes,
	}.Build()
	File_internal_igservice_igservice_proto = out.File
	file_internal_igservice_igservice_proto_rawDesc = nil
	file_internal_igservice_igservice_proto_goTypes = nil
	file_internal_igservice_igservice_proto_depIdxs = nil
}
