name: CD

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted
    environment: production

    steps:
      - uses: actions/checkout@v3
      - name: shut down the image
        run: docker-compose down
      - name: remove dangling images
        run: docker image prune --all --force
      - name: rebuild the image
        run: docker-compose build --no-cache
      - name: run the image
        run: docker-compose up -d

    env:
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}
      FILE_URL_PREFIX: ${{ vars.FILE_URL_PREFIX }}
      IG_SERVICE_URL: ${{ vars.IG_SERVICE_URL }}
      IG_SERVICE_SECRET: ${{ vars.IG_SERVICE_SECRET }}
